[workspace]
resolver = "2"

members = [
    "example-proto",
    "example-telnet",
    "protocolsocket-prost",
    "protocolsocket-server",
]

[workspace.dependencies]
protocolsocket-server   = { path = "protocolsocket-server" }
protocolsocket-prost    = { path = "protocolsocket-prost" }

bytes                   = { version = "1.6" }
env_logger              = { version = "0.11" }
futures                 = { version = "0.3" }
log                     = { version = "0.4" }
mio                     = { version = "1.0" }
prost                   = { version = "0.13" }
thiserror               = { version = "1.0" }
tokio                   = { version = "1.39" }
