[workspace]
resolver = "2"

members = [
    "example-proto",
    "example-telnet",
    "protosocket-client",
    "protosocket-connection",
    "protosocket-prost",
    "protosocket-server",
]

[workspace.dependencies]
protosocket-connection  = { path = "protosocket-connection" }
protosocket-server      = { path = "protosocket-server" }
protosocket-prost       = { path = "protosocket-prost" }

bytes                   = { version = "1.6" }
env_logger              = { version = "0.11" }
futures                 = { version = "0.3" }
log                     = { version = "0.4" }
mio                     = { version = "1.0" }
prost                   = { version = "0.13" }
thiserror               = { version = "1.0" }
tokio                   = { version = "1.39" }
tokio-util              = { version = "0.7" }
