[package]
name = "protocolsocket-prost"
version = "0.1.0"
edition = "2021"

[dependencies]
protocolsocket-server   = { workspace = true }

bytes                   = { workspace = true }
log                     = { workspace = true }
prost                   = { workspace = true }
