[package]
name = "protosocket-server"
version = "0.1.0"
edition = "2021"

[dependencies]
protosocket-connection  = { workspace = true }

bytes                   = { workspace = true }
futures                 = { workspace = true }
log                     = { workspace = true }
mio                     = { workspace = true, features = ["net", "os-poll"] }
thiserror               = { workspace = true }
tokio                   = { workspace = true }
